version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: touchline-backend
    environment:
      - DATABASE_URL=sqlite:///./touchline.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app
      - /app/venv
    ports:
      - "8000:8000"
    networks:
      - touchline-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: touchline-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-development-secret-key}
      - NEXTAUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - touchline-network
    restart: unless-stopped

networks:
  touchline-network:
    driver: bridge 